services:

  db:
    image: postgres:16
    container_name: cafeteria_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - cafeteria_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    container_name: cafeteria_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - cafeteria_odoo_data:/var/lib/odoo
      - ./modulo_cafeteria:/mnt/extra-addons/modulo_cafeteria
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    restart: unless-stopped

volumes:
  cafeteria_db_data:
  cafeteria_odoo_data: